<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>test</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>
	<body>
  
  		<form class="col-lg-8" id="contact-form">
  		  	<div class="form-row">
			<div class="col">
			    <label for="inputEmail4">First Name</label>
			    <input type="text" class="form-control" placeholder="First name" name="firstname" class="ignore">

			</div>
			<div class="col">
			      <label for="inputEmail4">Last Name</label>
			      <input type="text" class="form-control" placeholder="Last name" name="lastname" class="ignore">
			
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputEmail4">Email</label>
			      <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email" class="ignore">
			   

              	
			    </div>
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Password</label>
			      <input type="password" class="form-control" id="inputPassword4" placeholder="Password" name="password" class="ignore">
			     
			    </div>
			  </div>
		
			 
			
			 
			  
			  <button type="submit" class="btn btn-primary" id="save-contact" name="submit">Sign in</button>
			</form>
			<div id="affichage"></div>

			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

			 <script 
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous">
              </script>

              <script src="http://cdn.jsdelivr.net/jquery.validation/1.14.0/jquery.validate.min.js"></script>
		

            <script type="text/javascript">

           
		$(document ).ready(function() {

		
			
           $("#contact-form").validate({
				  rules : {
				    firstname : {
				    required : true
				    },

				    lastname : {
				      minlength : 3
				    },

				    email : {
				    required : true,
				    
				    }
				  },
				  messages : {
				    firstname : "Veuillez fournir un prénom",
				    lastname : "Veuillez fournir un nom d'au moins trois lettres",
				    email: "L'email est incorrect"
				  },
				

            errorClass:"help-inline text-danger",
        	errorElement:"span",
        	highlight: function(element, errorClass, validClass) {
            $(element).parents('.form-group').addClass('has-error');
        	},
        	unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.form-group').removeClass('has-error');
            $(element).parents('.form-group').addClass('has-success');
        	},

            submitHandler: function(form,e){

            e.preventDefault();

            $('#affichage').empty();
			var form=$('#contact-form')
			var donne=$('#contact-form').serialize();
			
				$.ajax({
					    url:"soft.php",
						method:"POST",
						data:donne,
						dataType:'JSON',
						
					    success:function(result){ 
							
						form[0].reset();
							
						$.each(result,function(index,value){
                          
                         $("#affichage").append("<p>id:"+value.id+"</p><p>firstname:"+value.firstname+"</p><p>lasttname:"+value.lastname+"</p>");
							
						});

						 
						 
						  
					   }
					});

			}

			});
		});

  
			</script>
	</body>
</html>